version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    network_mode: 'host'
    volumes:
      - /mnt/MovieMonster/.jellyfin/config:/config
      - /mnt/MovieMonster/.jellyfin/cache:/cache
      - /mnt/MovieMonster:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'
