version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    ports:
    - "8096:8096"
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    network_mode: 'host'
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/MovieMonster:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #Arc A380 for Av1 transcoding
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # depends_on:
    #   - tailscale
    restart: 'unless-stopped'
volumes:
  config:
    driver: local
  cache:
    driver: local
